services:
  ollama-node:
    image: ollama/ollama:latest
    container_name: ollama-node
    ports:
      - "11434:11434"
    environment:
      - USE_MMAP=true
      - NUM_THREAD=6
      - NUM_GPU=1

  nodeapp:
    build: .
    container_name: node_app
    depends_on:
      - ollama-node
    ports:
      - "3000:3000"
    environment:
      - OLLAMA_BASE_URL=http://ollama-node:11434